name: Code Analysis

on:
  workflow_dispatch:

jobs:
  code-analysis:
    runs-on: ubuntu-latest
    container:
      image: python:3.13

    steps:
      - name: Checkout the Repository to Runner
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: pip install -r requirements.txt --upgrade

      - name: Analysis pylint
        run: |
          pylint helpers locators tests conftest.py --reports=y --recursive=y --output-format=colorized --fail-on=E --fail-under=7
      
      - name: Analysis bandit
        if: always()
        run: |
          bandit -r helpers tests conftest.py
