name: Test Execution

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container: selenium/standalone-chrome
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v3

      - name: Install Dependencies
        run: pip install -r requirement.txt --upgrade

      - name: Test Execution
        run: pytest --html=test-results/report.html

      - uses: actions/upload-artifact@v4.6.2
        with:
          name: test-results
          path: test-results
          retention-days: 1
