name: Test Execution

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: selenium/standalone-chrome
      options: --user root

    steps:
      - name: Checkout the repository source code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v3

      - name: Install Dependencies
        run: pip install -r requirements.txt --upgrade

      - name: Test Execution
        run: pytest --headless

      - name: Upload Test Results
        uses: actions/upload-artifact@v4.6.2
        with:
          name: test-results
          path: test-results
          retention-days: 1
